// Datos completos de todas las recetas
const recipesData = {
    almuerzos: [
        // CARNES ROJAS
        { id: 'alm1', num: 1, title: 'Bifes a la criolla', desc: 'Con cebolla, pimiento y papas en cacerola + ensalada de zanahoria, tomate y huevo', time: 45, cal: 480, prot: 42, diff: 'Media', badges: ['protein', 'carbs'], category: 'Carnes Rojas', instructions: '1. Cortar cebolla y pimiento en juliana, papas en cubos\n2. En cacerola, saltear cebolla y pimiento con aceite\n3. Agregar los bifes y dorar de ambos lados\n4. Añadir papas y caldo de verduras para cubrir\n5. Cocinar a fuego medio hasta que las papas estén tiernas (30-35 min)\n6. Preparar ensalada: rallar zanahoria, cortar tomate, hervir huevo\n7. Servir los bifes con las papas y acompañar con la ensalada' },
        { id: 'alm2', num: 2, title: 'Carne al horno con verduras', desc: 'Roast beef con calabaza, zanahoria y cebolla asadas', time: 60, cal: 420, prot: 45, diff: 'Fácil', badges: ['protein', 'easy'], category: 'Carnes Rojas', instructions: '1. Precalentar el horno a 180°C\n2. Cortar calabaza, zanahoria y cebolla en trozos medianos\n3. Condimentar el roast beef con sal, pimienta y ajo\n4. Colocar la carne en una fuente para horno rodeada de las verduras\n5. Rociar con un poco de aceite y agregar hierbas aromáticas\n6. Hornear durante 50-60 minutos hasta que la carne esté tierna\n7. Dejar reposar 5 minutos antes de cortar y servir' },
        { id: 'alm3', num: 3, title: 'Bife de chorizo a la plancha', desc: 'Con ensalada mixta (lechuga, tomate, zanahoria rallada)', time: 20, cal: 520, prot: 48, diff: 'Fácil', badges: ['protein', 'quick'], category: 'Carnes Rojas', instructions: '1. Sacar el bife de la heladera 10 minutos antes de cocinar\n2. Condimentar con sal y pimienta de ambos lados\n3. Calentar bien la plancha o sartén\n4. Cocinar el bife 3-4 minutos de cada lado para término medio\n5. Mientras tanto, lavar y cortar lechuga y tomate\n6. Rallar la zanahoria\n7. Servir el bife con la ensalada mixta y condimentar al gusto' },
        { id: 'alm4', num: 4, title: 'Estofado de carne', desc: 'Con papas, zanahorias y arvejas', time: 50, cal: 460, prot: 40, diff: 'Media', badges: ['protein', 'carbs'], category: 'Carnes Rojas', instructions: '1. Cortar la carne en cubos medianos y dorar en una olla con aceite\n2. Picar cebolla y agregar a la carne, rehogar hasta que esté transparente\n3. Cortar papas y zanahorias en trozos\n4. Agregar a la olla junto con las arvejas\n5. Cubrir con caldo o agua, condimentar con sal, pimienta y laurel\n6. Cocinar a fuego medio-bajo durante 40-45 minutos\n7. Verificar que todo esté tierno y servir caliente' },
        { id: 'alm5', num: 5, title: 'Carne a la cacerola', desc: 'Con puré de calabaza', time: 40, cal: 440, prot: 43, diff: 'Fácil', badges: ['protein', 'easy'], category: 'Carnes Rojas', instructions: '1. Cortar la carne en trozos y condimentar con sal y pimienta\n2. En una cacerola, dorar la carne con un poco de aceite\n3. Agregar cebolla picada, ajo y pimiento si deseas\n4. Añadir caldo y cocinar a fuego medio 30-35 minutos\n5. Mientras tanto, hervir calabaza cortada en cubos hasta que esté tierna\n6. Hacer puré con la calabaza, agregar un poco de leche y condimentar\n7. Servir la carne con el puré de calabaza' },

        // CERDO
        { id: 'alm6', num: 6, title: 'Bondiola al horno', desc: 'Con salsa de tomate + batatas y calabacín al horno', time: 55, cal: 500, prot: 44, diff: 'Media', badges: ['protein'], category: 'Cerdo', instructions: '1. Precalentar el horno a 180°C\n2. Condimentar la bondiola con sal, pimienta, ajo y hierbas\n3. Dorarla en una sartén de ambos lados\n4. Colocar en una fuente y cubrir con salsa de tomate\n5. Cortar batatas y calabacín en rodajas, colocar alrededor\n6. Rociar las verduras con aceite y condimentar\n7. Hornear durante 45-50 minutos hasta que todo esté tierno\n8. Servir caliente' },
        { id: 'alm7', num: 7, title: 'Carré de cerdo', desc: 'A la cacerola con verduras', time: 45, cal: 470, prot: 42, diff: 'Media', badges: ['protein'], category: 'Cerdo', instructions: '1. Condimentar el carré de cerdo con sal, pimienta y pimentón\n2. En una cacerola grande, dorar el carré con aceite de todos lados\n3. Agregar cebolla, zanahoria, pimiento y apio cortados\n4. Añadir caldo de verduras para cubrir la mitad del carré\n5. Cocinar tapado a fuego medio durante 35-40 minutos\n6. Dar vuelta a mitad de cocción\n7. Verificar que esté tierno, dejar reposar 5 minutos y cortar en medallones\n8. Servir con las verduras y un poco del jugo de cocción' },
        { id: 'alm8', num: 8, title: 'Costeleta de cerdo a la plancha', desc: 'Con ensalada de repollo y zanahoria', time: 25, cal: 490, prot: 46, diff: 'Fácil', badges: ['protein', 'quick'], category: 'Cerdo', instructions: '1. Condimentar las costeletas con sal, pimienta y ajo en polvo\n2. Calentar bien la plancha o sartén\n3. Cocinar las costeletas 5-6 minutos de cada lado hasta que estén doradas\n4. Mientras tanto, rallar repollo y zanahoria finamente\n5. Preparar la ensalada mezclando ambas verduras\n6. Condimentar la ensalada con limón, aceite, sal y pimienta\n7. Servir las costeletas con la ensalada fresca al lado' },
        { id: 'alm9', num: 9, title: 'Solomillo de cerdo', desc: 'Con puré mixto (papa y batata)', time: 30, cal: 450, prot: 45, diff: 'Fácil', badges: ['protein', 'quick'], category: 'Cerdo', instructions: '1. Condimentar el solomillo con sal, pimienta y hierbas aromáticas\n2. Sellar en sartén caliente de todos lados hasta dorar\n3. Terminar la cocción en el horno a 180°C por 15-20 minutos\n4. Mientras tanto, hervir papas y batatas peladas en cubos\n5. Una vez tiernas, escurrir y hacer puré\n6. Agregar un poco de leche, sal y nuez moscada al puré\n7. Dejar reposar el solomillo 5 minutos, cortar en medallones y servir con el puré' },

        // POLLO
        { id: 'alm10', num: 10, title: 'Suprema de pollo al horno', desc: 'Con puré de calabaza', time: 35, cal: 380, prot: 48, diff: 'Fácil', badges: ['protein', 'easy'], category: 'Pollo', instructions: '1. Precalentar el horno a 180°C\n2. Condimentar las supremas con sal, pimienta, ajo y limón\n3. Colocar en una fuente para horno con un poco de aceite\n4. Hornear durante 25-30 minutos hasta que estén doradas\n5. Mientras tanto, hervir calabaza cortada en cubos hasta que esté tierna\n6. Hacer puré con la calabaza, agregar un poco de leche y condimentar\n7. Servir las supremas con el puré de calabaza' },
        { id: 'alm11', num: 11, title: 'Pollo al verdeo', desc: 'Con arroz (1 pocillo en crudo)', time: 40, cal: 420, prot: 45, diff: 'Media', badges: ['protein', 'carbs'], category: 'Pollo', instructions: '1. Cortar el pollo en presas y condimentar con sal y pimienta\n2. Dorar el pollo en una sartén grande con aceite\n3. Picar abundante verdeo (parte blanca y verde)\n4. Agregar el verdeo al pollo y rehogar 2 minutos\n5. Añadir caldo o agua, tapar y cocinar 25-30 minutos\n6. Mientras tanto, cocinar el arroz: hervir 2 pocillos de agua, agregar 1 pocillo de arroz\n7. Cocinar el arroz tapado a fuego bajo por 15-18 minutos\n8. Servir el pollo al verdeo sobre el arroz' },
        { id: 'alm12', num: 12, title: 'Muslo de pollo al horno', desc: 'Con ensalada de remolacha y huevo', time: 45, cal: 400, prot: 42, diff: 'Fácil', badges: ['protein', 'easy'], category: 'Pollo', instructions: '1. Precalentar el horno a 180°C\n2. Condimentar los muslos de pollo con sal, pimienta, ajo y pimentón\n3. Colocar en una fuente para horno con un poco de aceite y limón\n4. Hornear durante 40-45 minutos hasta que estén dorados y cocidos\n5. Hervir huevos hasta que estén duros (10 minutos)\n6. Cocinar remolacha hervida si no está cocida, cortar en cubos\n7. Pelar y cortar los huevos en cuartos\n8. Mezclar remolacha y huevo, condimentar con aceite, sal y limón\n9. Servir los muslos con la ensalada' },
        { id: 'alm13', num: 13, title: 'Pollo a la cacerola', desc: 'Con papas y zanahorias', time: 50, cal: 410, prot: 44, diff: 'Media', badges: ['protein', 'carbs'], category: 'Pollo', instructions: '1. Cortar el pollo en presas y condimentar con sal y pimienta\n2. En una cacerola, dorar el pollo con aceite de todos lados\n3. Agregar cebolla picada y rehogar hasta que esté transparente\n4. Pelar y cortar papas y zanahorias en trozos medianos\n5. Añadir las verduras a la cacerola\n6. Cubrir con caldo o agua, agregar laurel y hierbas aromáticas\n7. Cocinar tapado a fuego medio durante 40-45 minutos\n8. Verificar que todo esté tierno y servir caliente' },

        // MILANESAS
        { id: 'alm14', num: 14, title: 'Milanesa de pollo', desc: 'Con ensalada de rúcula, tomate, choclo y huevo duro', time: 25, cal: 450, prot: 46, diff: 'Fácil', badges: ['protein', 'quick'], category: 'Milanesas', instructions: '1. Condimentar las supremas de pollo con sal y pimienta\n2. Pasar por huevo batido y luego por pan rallado\n3. Freír en sartén con aceite caliente hasta dorar de ambos lados\n4. Colocar sobre papel absorbente para quitar exceso de aceite\n5. Hervir huevos hasta que estén duros (10 minutos)\n6. Lavar rúcula, cortar tomate en cubos\n7. Mezclar rúcula, tomate, choclo y huevo duro cortado\n8. Condimentar la ensalada y servir junto a las milanesas' },
        { id: 'alm15', num: 15, title: 'Milanesa de carne', desc: 'Con ensalada completa (lechuga, tomate, zanahoria, huevo)', time: 25, cal: 470, prot: 45, diff: 'Fácil', badges: ['protein', 'quick'], category: 'Milanesas', instructions: '1. Condimentar los bifes con sal y pimienta\n2. Pasar por huevo batido y luego por pan rallado presionando bien\n3. Freír en aceite caliente hasta que estén doradas y crocantes\n4. Retirar y escurrir sobre papel absorbente\n5. Hervir huevos hasta que estén duros (10 minutos)\n6. Lavar y cortar lechuga y tomate, rallar zanahoria\n7. Pelar y cortar los huevos\n8. Mezclar todas las verduras, condimentar y servir con las milanesas' },
        { id: 'alm16', num: 16, title: 'Milanesa napolitana', desc: 'Con ensalada verde (sin pan)', time: 30, cal: 520, prot: 48, diff: 'Media', badges: ['protein'], category: 'Milanesas', instructions: '1. Preparar la milanesa: condimentar, pasar por huevo y pan rallado\n2. Freír la milanesa en aceite caliente hasta dorar de ambos lados\n3. Colocar en una fuente para horno\n4. Cubrir con rodajas de tomate, jamón y queso mozzarella\n5. Llevar al horno a 180°C por 10 minutos hasta que el queso se derrita\n6. Mientras tanto, lavar y cortar lechuga, rúcula u otras hojas verdes\n7. Condimentar la ensalada con aceite, limón y sal\n8. Servir la napolitana con la ensalada verde' },

        // TARTAS Y VEGETARIANAS
        { id: 'alm17', num: 17, title: 'Tarta de zapallito con carne molida', desc: 'Sin tapa, 1/4 de unidad + ensalada de zanahoria rallada', time: 50, cal: 360, prot: 28, diff: 'Media', badges: ['carbs'], category: 'Tartas y Vegetarianas', instructions: '1. Precalentar el horno a 180°C\n2. Forrar un molde con masa para tarta\n3. Saltear cebolla picada, agregar carne molida y cocinar\n4. Cortar zapallitos en rodajas finas y saltear por separado\n5. Mezclar carne, zapallitos y 2-3 huevos batidos, condimentar\n6. Volcar el relleno sobre la masa (sin colocar tapa)\n7. Hornear 35-40 minutos hasta que cuaje y dore\n8. Rallar zanahoria, condimentar con limón y aceite\n9. Servir una porción de tarta con la ensalada' },
        { id: 'alm18', num: 18, title: 'Tarta de acelga y huevo', desc: 'Sin tapa + ensalada de tomate', time: 45, cal: 320, prot: 24, diff: 'Media', badges: ['carbs', 'easy'], category: 'Tartas y Vegetarianas', instructions: '1. Precalentar el horno a 180°C\n2. Forrar un molde con masa para tarta\n3. Lavar y hervir acelga, escurrir bien y picar\n4. Saltear cebolla picada hasta que esté transparente\n5. Mezclar acelga, cebolla, 3 huevos batidos, sal y pimienta\n6. Volcar el relleno sobre la masa (sin tapa)\n7. Hornear 30-35 minutos hasta que cuaje y dore\n8. Mientras tanto, cortar tomates en rodajas y condimentar\n9. Servir la tarta con la ensalada de tomate' },
        { id: 'alm19', num: 19, title: 'Hamburguesas vegetarianas (2)', desc: 'Con ensalada de chauchas y huevo duro', time: 30, cal: 340, prot: 22, diff: 'Fácil', badges: ['carbs', 'quick'], category: 'Tartas y Vegetarianas', instructions: '1. Procesar garbanzos cocidos o lentejas con cebolla, ajo y especias\n2. Agregar pan rallado y huevo para formar la masa\n3. Formar 2 hamburguesas y condimentar con sal y pimienta\n4. Cocinar en sartén con aceite 4-5 minutos de cada lado hasta dorar\n5. Hervir chauchas hasta que estén tiernas pero firmes\n6. Hervir huevos hasta que estén duros (10 minutos)\n7. Cortar las chauchas y los huevos\n8. Mezclar en ensalada, condimentar con limón, aceite y sal\n9. Servir las hamburguesas con la ensalada' },
        { id: 'alm20', num: 20, title: 'Quinoa/Arroz con verduras salteadas', desc: 'Cebolla, pimiento, zanahoria, berenjena (1 pocillo crudo)', time: 35, cal: 380, prot: 18, diff: 'Fácil', badges: ['carbs', 'easy'], category: 'Tartas y Vegetarianas', instructions: '1. Enjuagar 1 pocillo de quinoa o arroz\n2. Cocinar en 2 pocillos de agua con sal por 15-20 minutos\n3. Mientras tanto, cortar cebolla, pimiento, zanahoria y berenjena en cubos\n4. En un wok o sartén grande, saltear las verduras con aceite\n5. Comenzar por la cebolla, luego agregar las demás verduras\n6. Condimentar con sal, pimienta, ajo y hierbas aromáticas\n7. Cocinar 10-12 minutos hasta que estén tiernas pero firmes\n8. Mezclar las verduras con la quinoa/arroz cocido y servir' },

        // PASTAS Y ASADO
        { id: 'alm21', num: 21, title: 'Fideos con boloñesa', desc: 'Porción moderada con 1 cda de queso rallado', time: 40, cal: 480, prot: 32, diff: 'Media', badges: ['carbs'], category: 'Pastas y Asado', instructions: '1. Poner agua con sal a hervir para los fideos\n2. En una sartén, saltear cebolla picada con aceite\n3. Agregar carne molida y dorar, desmenuzando bien\n4. Añadir tomate triturado o salsa de tomate, condimentar\n5. Cocinar la salsa boloñesa a fuego medio 25-30 minutos\n6. Agregar albahaca, orégano y laurel al gusto\n7. Cocinar los fideos según el tiempo del paquete\n8. Escurrir los fideos y mezclar con la salsa boloñesa\n9. Servir con 1 cucharada de queso rallado por encima' },
        { id: 'alm22', num: 22, title: 'Asado de carne o pollo', desc: 'Con ensalada mixta', time: 90, cal: 550, prot: 50, diff: 'Media', badges: ['protein'], category: 'Pastas y Asado', instructions: '1. Preparar el fuego o precalentar la parrilla\n2. Condimentar la carne o pollo con sal gruesa\n3. Si es carne vacuna, comenzar con cortes más gruesos primero\n4. Si es pollo, colocar las presas con la piel hacia arriba inicialmente\n5. Cocinar dando vuelta ocasionalmente hasta lograr cocción deseada\n6. La carne vacuna toma 60-90 minutos, el pollo 45-60 minutos\n7. Mientras tanto, preparar ensalada con lechuga, tomate, zanahoria\n8. Condimentar la ensalada al momento de servir\n9. Servir el asado con la ensalada mixta' },
        { id: 'alm23', num: 23, title: 'Ravioles de verdura', desc: 'Con salsa fileto (sin repetir)', time: 25, cal: 420, prot: 26, diff: 'Fácil', badges: ['carbs', 'quick'], category: 'Pastas y Asado', instructions: '1. Poner abundante agua con sal a hervir\n2. Mientras tanto, preparar la salsa: saltear ajo picado en aceite\n3. Agregar tomate triturado o salsa de tomate\n4. Condimentar con sal, pimienta, albahaca y orégano\n5. Cocinar la salsa 15 minutos a fuego medio\n6. Cuando el agua hierva, agregar los ravioles con cuidado\n7. Cocinar según indicaciones del paquete (generalmente 8-10 minutos)\n8. Escurrir los ravioles y mezclar con la salsa fileto\n9. Servir una porción moderada sin repetir' }
    ],

    meriendas: [
        // CON YOGUR
        { id: 'mer1', num: 1, title: 'Yogur con granola y durazno', desc: '1 taza yogur + 2 cdas granola + 1 fruta en trozos', time: 5, cal: 280, prot: 12, diff: 'Fácil', badges: ['quick', 'easy'], category: 'Con Yogur', instructions: '1. Servir 1 taza de yogur natural o descremado en un bol\n2. Lavar y cortar el durazno en trozos\n3. Agregar los trozos de durazno sobre el yogur\n4. Espolvorear 2 cucharadas de granola por encima\n5. Mezclar suavemente y disfrutar' },
        { id: 'mer2', num: 2, title: 'Yogur con granola y ciruela', desc: '1 taza yogur + 2 cdas granola + ciruela picada', time: 5, cal: 270, prot: 12, diff: 'Fácil', badges: ['quick', 'easy'], category: 'Con Yogur', instructions: '1. Servir 1 taza de yogur natural o descremado en un bol\n2. Lavar y cortar las ciruelas en trozos pequeños\n3. Agregar las ciruelas picadas sobre el yogur\n4. Espolvorear 2 cucharadas de granola por encima\n5. Mezclar y servir inmediatamente' },
        { id: 'mer3', num: 3, title: 'Yogur con granola y banana', desc: '1 taza yogur + 2 cdas granola + 1/2 banana', time: 5, cal: 290, prot: 13, diff: 'Fácil', badges: ['quick', 'easy'], category: 'Con Yogur', instructions: '1. Servir 1 taza de yogur natural o descremado en un bol\n2. Pelar y cortar media banana en rodajas\n3. Colocar las rodajas de banana sobre el yogur\n4. Agregar 2 cucharadas de granola por encima\n5. Mezclar todo y disfrutar' },
        { id: 'mer4', num: 4, title: 'Yogur con frutas del bosque', desc: '1 taza yogur + mix de berries + 1 cda granola', time: 5, cal: 260, prot: 11, diff: 'Fácil', badges: ['quick', 'easy'], category: 'Con Yogur', instructions: '1. Servir 1 taza de yogur natural o descremado en un bol\n2. Lavar las frutas del bosque (frutillas, arándanos, frambuesas)\n3. Agregar el mix de berries sobre el yogur\n4. Espolvorear 1 cucharada de granola por encima\n5. Mezclar suavemente y servir' },

        // CON GELATINA
        { id: 'mer5', num: 5, title: 'Gelatina con yogur y granola', desc: '1 porción gelatina + 1/2 taza yogur + 2 cdas granola', time: 5, cal: 220, prot: 10, diff: 'Fácil', badges: ['quick', 'easy'], category: 'Con Gelatina', instructions: '1. Preparar la gelatina según instrucciones del paquete y refrigerar hasta que cuaje\n2. Servir 1 porción de gelatina en un bol\n3. Agregar media taza de yogur natural por encima\n4. Espolvorear 2 cucharadas de granola\n5. Servir inmediatamente' },
        { id: 'mer6', num: 6, title: 'Gelatina con frutas', desc: '1 porción gelatina + trozos de fruta fresca', time: 5, cal: 180, prot: 6, diff: 'Fácil', badges: ['quick', 'easy'], category: 'Con Gelatina', instructions: '1. Preparar la gelatina según instrucciones del paquete y refrigerar\n2. Lavar y cortar frutas frescas en trozos pequeños\n3. Cuando la gelatina esté semi-cuajada, agregar los trozos de fruta\n4. Refrigerar hasta que cuaje completamente\n5. Servir una porción en un bol' },

        // LICUADOS
        { id: 'mer7', num: 7, title: 'Licuado de durazno', desc: '1 vaso leche + 2 duraznos + edulcorante. Acompañar con: 1 rollito jamón y queso', time: 10, cal: 320, prot: 18, diff: 'Fácil', badges: ['protein', 'quick'], category: 'Licuados', instructions: '1. Pelar y cortar los duraznos\n2. Colocar en licuadora con la leche y edulcorante\n3. Licuar hasta que quede homogéneo\n4. Servir y acompañar con 1 rollito de jamón y queso (comido aparte)' },
        { id: 'mer8', num: 8, title: 'Licuado de banana', desc: '1 vaso leche + 1 banana + edulcorante. Acompañar con: 1 rollito jamón y queso', time: 10, cal: 330, prot: 18, diff: 'Fácil', badges: ['protein', 'quick'], category: 'Licuados', instructions: '1. Pelar y cortar la banana\n2. Colocar en licuadora con la leche y edulcorante\n3. Licuar hasta que quede cremoso\n4. Servir y acompañar con 1 rollito de jamón y queso (comido aparte)' },
        { id: 'mer9', num: 9, title: 'Licuado de frutilla', desc: '1 vaso leche + frutillas + edulcorante. Acompañar con: 1 rollito jamón y queso', time: 10, cal: 310, prot: 17, diff: 'Fácil', badges: ['protein', 'quick'], category: 'Licuados', instructions: '1. Lavar y cortar las frutillas\n2. Colocar en licuadora con la leche y edulcorante\n3. Licuar hasta obtener consistencia suave\n4. Servir y acompañar con 1 rollito de jamón y queso (comido aparte)' },

        // CON INFUSION Y PAN INTEGRAL
        { id: 'mer10', num: 10, title: 'Té/café con leche + tostadas', desc: '2 rodajas pan integral con queso y dulce de membrillo', time: 10, cal: 300, prot: 14, diff: 'Fácil', badges: ['carbs', 'quick'], category: 'Con Infusión y Pan', instructions: '1. Preparar té o café con leche caliente\n2. Tostar 2 rodajas de pan integral hasta que estén doradas\n3. Untar con queso crema o queso untable\n4. Agregar unas rodajas finas de dulce de membrillo por encima\n5. Servir las tostadas con la infusión caliente' },
        { id: 'mer11', num: 11, title: 'Té/café con leche + tostadas con queso untable', desc: '2 rodajas pan integral + queso blanco', time: 10, cal: 280, prot: 15, diff: 'Fácil', badges: ['carbs', 'quick'], category: 'Con Infusión y Pan', instructions: '1. Preparar té o café con leche caliente al gusto\n2. Tostar 2 rodajas de pan integral hasta que estén crocantes\n3. Untar generosamente con queso blanco o queso untable\n4. Condimentar con hierbas si lo deseas\n5. Servir las tostadas acompañadas de la infusión' },
        { id: 'mer12', num: 12, title: 'Infusión con pan y jamón', desc: '2 rodajas pan integral con jamón y queso', time: 10, cal: 310, prot: 16, diff: 'Fácil', badges: ['carbs', 'quick'], category: 'Con Infusión y Pan', instructions: '1. Preparar la infusión de tu preferencia (té o café con leche)\n2. Tostar 2 rodajas de pan integral\n3. Colocar jamón cocido sobre cada tostada\n4. Agregar una feta de queso por encima\n5. Opcionalmente, gratinar en horno o microondas 30 segundos\n6. Servir con la infusión caliente' },

        // OPCIONES RAPIDAS
        { id: 'mer13', num: 13, title: 'Fruta + puñado de frutos secos', desc: '1 manzana/pera + 4 nueces', time: 2, cal: 220, prot: 6, diff: 'Fácil', badges: ['quick', 'easy'], category: 'Opciones Rápidas', instructions: '1. Lavar bien la manzana o pera\n2. Cortar la fruta en trozos o comer entera\n3. Servir acompañada de 4 nueces o un puñado de frutos secos\n4. Disfrutar como merienda rápida y saludable' },
        { id: 'mer14', num: 14, title: 'Yogur solo con fruta', desc: '1 vaso yogur sin azúcar + 1 fruta picada', time: 5, cal: 200, prot: 10, diff: 'Fácil', badges: ['quick', 'easy'], category: 'Opciones Rápidas', instructions: '1. Servir 1 vaso de yogur natural sin azúcar en un bol\n2. Lavar y cortar la fruta de tu elección en trozos\n3. Agregar la fruta picada al yogur\n4. Mezclar suavemente y servir\n5. Puedes agregar edulcorante si lo deseas' },
        { id: 'mer15', num: 15, title: 'Rollitos de jamón y queso (2-3)', desc: 'Con tomates cherry', time: 5, cal: 180, prot: 14, diff: 'Fácil', badges: ['protein', 'quick'], category: 'Opciones Rápidas', instructions: '1. Extender 2-3 fetas de jamón cocido\n2. Colocar una feta de queso sobre cada feta de jamón\n3. Enrollar formando rollitos\n4. Asegurar con un palillo si es necesario\n5. Lavar tomates cherry y servir como acompañamiento\n6. Disfrutar como merienda proteica' }
    ],

    cenas: [
        // A BASE DE HUEVO
        { id: 'cen1', num: 1, title: 'Tortilla de zapallito', desc: 'Con papas hervidas', time: 25, cal: 340, prot: 18, diff: 'Fácil', badges: ['protein', 'easy'], category: 'A Base de Huevo', instructions: '1. Lavar y cortar los zapallitos en rodajas finas\n2. Saltear los zapallitos en sartén con un poco de aceite hasta que estén tiernos\n3. Batir 3-4 huevos con sal y pimienta\n4. Agregar los zapallitos a los huevos batidos\n5. Cocinar en sartén a fuego medio hasta que cuaje de un lado\n6. Dar vuelta con ayuda de un plato y cocinar del otro lado\n7. Hervir papas en agua con sal hasta que estén tiernas\n8. Servir la tortilla con las papas hervidas' },
        { id: 'cen2', num: 2, title: 'Huevos al colchón de arvejas', desc: '2 huevos sobre arvejas con cebolla y pimiento salteados', time: 20, cal: 320, prot: 20, diff: 'Fácil', badges: ['protein', 'quick'], category: 'A Base de Huevo', instructions: '1. Picar cebolla y pimiento en trozos pequeños\n2. Saltear la cebolla y pimiento en sartén con aceite\n3. Agregar arvejas (frescas o congeladas) y cocinar 5 minutos\n4. Condimentar con sal, pimienta y ajo\n5. Hacer dos huecos en las verduras\n6. Cascar un huevo en cada hueco\n7. Tapar y cocinar hasta que los huevos estén a tu gusto\n8. Servir directamente de la sartén' },
        { id: 'cen3', num: 3, title: 'Omelete de verduras y queso', desc: 'Con tomate con albahaca u orégano', time: 15, cal: 300, prot: 22, diff: 'Fácil', badges: ['protein', 'quick'], category: 'A Base de Huevo', instructions: '1. Picar verduras de tu elección (cebolla, pimiento, espinaca)\n2. Saltear las verduras en una sartén con poco aceite\n3. Batir 2-3 huevos con sal y pimienta\n4. Verter los huevos sobre las verduras\n5. Agregar queso rallado por encima\n6. Cocinar hasta que cuaje, doblar por la mitad\n7. Cortar tomate en rodajas, condimentar con albahaca u orégano\n8. Servir el omelete con el tomate al lado' },
        { id: 'cen4a', num: 4, title: 'Omelete de atún y verduras', desc: 'Con verduras picadas + tomate con albahaca u orégano', time: 20, cal: 310, prot: 26, diff: 'Fácil', badges: ['protein', 'quick'], category: 'A Base de Huevo', instructions: '1. Escurrir bien una lata de atún al natural\n2. Picar verduras (cebolla, pimiento, tomate)\n3. Saltear las verduras en sartén con poco aceite\n4. Agregar el atún desmenuzado y mezclar\n5. Batir 2-3 huevos con sal y pimienta\n6. Verter los huevos sobre la mezcla de atún y verduras\n7. Cocinar hasta que cuaje y doblar por la mitad\n8. Servir con rodajas de tomate condimentadas con albahaca u orégano' },
        { id: 'cen4', num: 5, title: 'Tortilla española', desc: 'Con papa y cebolla + ensalada verde', time: 30, cal: 360, prot: 16, diff: 'Media', badges: ['carbs'], category: 'A Base de Huevo', instructions: '1. Pelar y cortar papas en rodajas finas\n2. Picar cebolla en juliana\n3. Freír papas y cebolla en aceite hasta que estén tiernas\n4. Escurrir bien y mezclar con 4-5 huevos batidos\n5. Dejar reposar 5 minutos\n6. Cocinar en sartén a fuego medio hasta dorar un lado\n7. Dar vuelta con ayuda de un plato y cocinar el otro lado\n8. Preparar ensalada verde y servir con la tortilla' },
        { id: 'cen5', num: 5, title: 'Huevos revueltos con verduras', desc: 'Con tomate y cebolla + ensalada', time: 15, cal: 280, prot: 18, diff: 'Fácil', badges: ['protein', 'quick'], category: 'A Base de Huevo', instructions: '1. Picar cebolla y tomate en cubos pequeños\n2. Saltear la cebolla en sartén con poco aceite hasta que esté transparente\n3. Agregar el tomate y cocinar 2 minutos\n4. Batir 2-3 huevos con sal y pimienta\n5. Verter los huevos sobre las verduras\n6. Revolver constantemente hasta que los huevos cuajen a tu gusto\n7. Preparar una ensalada fresca\n8. Servir los huevos revueltos con la ensalada' },
        { id: 'cen6', num: 6, title: 'Huevos a la plancha (2)', desc: 'Con jamón y queso + ensalada de tomate', time: 15, cal: 320, prot: 24, diff: 'Fácil', badges: ['protein', 'quick'], category: 'A Base de Huevo', instructions: '1. Calentar una sartén o plancha con un poco de aceite\n2. Cascar 2 huevos con cuidado en la sartén\n3. Cocinar a fuego medio hasta que las claras estén firmes\n4. Mientras tanto, cortar jamón y queso en trozos\n5. Agregar el jamón y queso alrededor de los huevos\n6. Cortar tomates en rodajas y condimentar\n7. Servir los huevos a la plancha con jamón, queso y ensalada de tomate' },

        // CARNES
        { id: 'cen7', num: 7, title: 'Lomo al plato', desc: 'Churrasco con jamón, queso y huevo a la plancha + tomate con orégano', time: 25, cal: 480, prot: 42, diff: 'Media', badges: ['protein'], category: 'Carnes', instructions: '1. Condimentar el churrasco de lomo con sal y pimienta\n2. Calentar bien la plancha o sartén\n3. Cocinar el churrasco 3-4 minutos de cada lado\n4. Colocar jamón y queso sobre el churrasco\n5. Freír un huevo a la plancha aparte\n6. Colocar el huevo sobre el churrasco con jamón y queso\n7. Cortar tomate en rodajas, condimentar con orégano y aceite\n8. Servir el lomo al plato con el tomate' },
        { id: 'cen8', num: 8, title: 'Bife a la plancha', desc: 'Con ensalada de tomate, lechuga y zanahoria', time: 20, cal: 440, prot: 45, diff: 'Fácil', badges: ['protein', 'quick'], category: 'Carnes', instructions: '1. Sacar el bife de la heladera 10 minutos antes\n2. Condimentar con sal y pimienta de ambos lados\n3. Calentar bien la plancha o sartén\n4. Cocinar el bife 3-4 minutos de cada lado según el término deseado\n5. Lavar y cortar lechuga y tomate\n6. Rallar zanahoria\n7. Mezclar todas las verduras en ensalada\n8. Condimentar la ensalada y servir con el bife' },
        { id: 'cen9', num: 9, title: 'Pollo grillado', desc: 'Con verduras al vapor o ensalada', time: 25, cal: 380, prot: 46, diff: 'Fácil', badges: ['protein', 'easy'], category: 'Carnes', instructions: '1. Condimentar las presas de pollo con sal, pimienta, ajo y limón\n2. Dejar marinar 10 minutos si tienes tiempo\n3. Calentar la parrilla o plancha\n4. Cocinar el pollo 10-12 minutos de cada lado hasta que esté dorado\n5. Verificar que esté bien cocido en el centro\n6. Mientras tanto, cocinar verduras al vapor o preparar ensalada\n7. Servir el pollo grillado con las verduras' },
        { id: 'cen10', num: 10, title: 'Salpicón de pollo', desc: 'Con papas, zanahoria, huevo duro y arvejas', time: 30, cal: 400, prot: 38, diff: 'Media', badges: ['protein', 'carbs'], category: 'Carnes', instructions: '1. Hervir pechuga de pollo en agua con sal hasta que esté cocida\n2. Hervir papas, zanahorias y arvejas hasta que estén tiernas\n3. Hervir huevos hasta que estén duros (10 minutos)\n4. Dejar enfriar todo y cortar en cubos\n5. Desmenuzar el pollo con las manos o tenedor\n6. Mezclar pollo, papas, zanahorias, arvejas y huevo\n7. Condimentar con mayonesa light, sal y pimienta\n8. Refrigerar y servir frío' },

        // ENSALADAS COMPLETAS
        { id: 'cen11', num: 11, title: 'Ensalada de lentejas', desc: 'Con tomate, choclo, daditos de queso y zanahoria rallada', time: 15, cal: 360, prot: 22, diff: 'Fácil', badges: ['carbs', 'quick'], category: 'Ensaladas Completas', instructions: '1. Usar lentejas cocidas (de lata o hervidas previamente)\n2. Enjuagar bien las lentejas y escurrir\n3. Cortar tomate en cubos y queso en daditos\n4. Rallar zanahoria\n5. Mezclar lentejas, tomate, choclo, queso y zanahoria\n6. Condimentar con aceite, vinagre o limón, sal y pimienta\n7. Agregar hierbas frescas si lo deseas\n8. Servir frío como plato principal' },
        { id: 'cen12', num: 12, title: 'Ensalada de pollo desmenuzado', desc: 'Con papa, huevo, tomate y arvejas', time: 25, cal: 420, prot: 40, diff: 'Fácil', badges: ['protein'], category: 'Ensaladas Completas', instructions: '1. Hervir pechuga de pollo en agua con sal hasta que esté cocida\n2. Hervir papas hasta que estén tiernas, cortar en cubos\n3. Hervir huevos hasta que estén duros (10 minutos) y cortar\n4. Cocinar arvejas (frescas o congeladas)\n5. Desmenuzar el pollo con tenedor\n6. Cortar tomate en cubos\n7. Mezclar todos los ingredientes en un bol\n8. Condimentar con mayonesa light, sal y pimienta' },
        { id: 'cen13', num: 13, title: 'Ensalada césar (sin croutones)', desc: 'Lechuga, pollo, parmesano, huevo', time: 20, cal: 380, prot: 42, diff: 'Fácil', badges: ['protein', 'quick'], category: 'Ensaladas Completas', instructions: '1. Cocinar pechuga de pollo a la plancha y cortar en tiras\n2. Hervir un huevo hasta que esté duro (10 minutos)\n3. Lavar y cortar lechuga romana en trozos grandes\n4. Preparar aderezo césar mezclando mostaza, limón, ajo y aceite\n5. Colocar la lechuga en un bol grande\n6. Agregar el pollo en tiras y el huevo cortado\n7. Rallar queso parmesano por encima\n8. Agregar el aderezo, mezclar y servir' },
        { id: 'cen14', num: 14, title: 'Ensalada de garbanzos', desc: 'Con tomate, pepino, cebolla morada y huevo', time: 15, cal: 340, prot: 20, diff: 'Fácil', badges: ['carbs', 'quick'], category: 'Ensaladas Completas', instructions: '1. Usar garbanzos cocidos (de lata o hervidos previamente)\n2. Enjuagar y escurrir bien los garbanzos\n3. Cortar tomate y pepino en cubos\n4. Picar cebolla morada finamente\n5. Hervir huevos hasta que estén duros y cortar en cuartos\n6. Mezclar garbanzos, tomate, pepino y cebolla\n7. Agregar los huevos por encima\n8. Condimentar con limón, aceite de oliva, sal y pimienta' },

        // PIZZA Y EMPANADAS
        { id: 'cen15', num: 15, title: 'Pizza integral', desc: '3 porciones, masa fina con harina integral', time: 45, cal: 520, prot: 28, diff: 'Media', badges: ['carbs'], category: 'Pizza y Empanadas', instructions: '1. Preparar masa integral o comprar pre-hecha\n2. Estirar la masa finamente sobre una pizzera\n3. Precalentar el horno a 220°C\n4. Cubrir con salsa de tomate\n5. Agregar queso mozzarella en cantidad moderada\n6. Añadir toppings de tu elección (jamón, verduras, aceitunas)\n7. Hornear 15-20 minutos hasta que el borde esté dorado\n8. Cortar en porciones y servir 3 porciones' },
        { id: 'cen16', num: 16, title: 'Empanadas', desc: '3 unidades (carne, pollo o verdura)', time: 50, cal: 480, prot: 26, diff: 'Media', badges: ['carbs'], category: 'Pizza y Empanadas', instructions: '1. Preparar el relleno: saltear carne, pollo o verduras con cebolla\n2. Condimentar con comino, pimentón, sal y pimienta\n3. Dejar enfriar el relleno\n4. Precalentar el horno a 200°C\n5. Colocar relleno en el centro de cada tapa de empanada\n6. Cerrar formando un repulgue en el borde\n7. Pincelar con huevo batido\n8. Hornear 20-25 minutos hasta que estén doradas\n9. Servir 3 empanadas calientes' },

        // OTRAS OPCIONES
        { id: 'cen17', num: 17, title: 'Tarta de verduras', desc: 'Sin tapa + ensalada', time: 45, cal: 320, prot: 18, diff: 'Media', badges: ['carbs'], category: 'Otras Opciones', instructions: '1. Precalentar el horno a 180°C\n2. Forrar un molde para tarta con masa\n3. Saltear verduras variadas (espinaca, acelga, pimiento, cebolla)\n4. Mezclar las verduras con 3 huevos batidos\n5. Condimentar con sal, pimienta y nuez moscada\n6. Volcar el relleno sobre la masa (sin tapa)\n7. Hornear 35-40 minutos hasta que cuaje y dore\n8. Preparar ensalada fresca y servir con una porción de tarta' },
        { id: 'cen18', num: 18, title: 'Sushi', desc: '8-12 piezas (ocasional)', time: 60, cal: 380, prot: 24, diff: 'Media', badges: ['carbs'], category: 'Otras Opciones', instructions: '1. Cocinar arroz para sushi y condimentar con vinagre de arroz\n2. Dejar enfriar el arroz completamente\n3. Preparar rellenos: cortar pescado, palta, pepino en tiras\n4. Colocar una lámina de nori sobre la esterilla de bambú\n5. Extender una capa fina de arroz sobre el nori\n6. Colocar los rellenos en el centro\n7. Enrollar firmemente usando la esterilla\n8. Cortar en 8-12 piezas y servir con salsa de soja' },
        { id: 'cen19', num: 19, title: 'Suprema grillada', desc: 'Con puré de calabaza', time: 30, cal: 360, prot: 44, diff: 'Fácil', badges: ['protein', 'easy'], category: 'Otras Opciones', instructions: '1. Condimentar la suprema de pollo con sal, pimienta, ajo y limón\n2. Calentar la parrilla o plancha\n3. Cocinar la suprema 6-7 minutos de cada lado hasta que esté dorada\n4. Verificar que esté bien cocida en el centro\n5. Mientras tanto, hervir calabaza cortada en cubos\n6. Hacer puré con la calabaza, agregar un poco de leche\n7. Condimentar el puré con sal y nuez moscada\n8. Servir la suprema grillada con el puré de calabaza' },
        { id: 'cen20', num: 20, title: 'Peceto frío', desc: 'Con ensalada rusa light (papa, zanahoria, arvejas, huevo, poco de mayonesa)', time: 40, cal: 400, prot: 38, diff: 'Media', badges: ['protein', 'carbs'], category: 'Otras Opciones', instructions: '1. Hervir el peceto en agua con sal, laurel y verduras por 40 minutos\n2. Dejar enfriar completamente y cortar en fetas finas\n3. Hervir papas y zanahorias, cortar en cubos pequeños\n4. Cocinar arvejas hasta que estén tiernas\n5. Hervir huevos hasta que estén duros (10 minutos) y picar\n6. Mezclar papa, zanahoria, arvejas y huevo\n7. Condimentar con poca mayonesa light, sal y pimienta\n8. Servir el peceto frío con la ensalada rusa' }
    ]
};

// Helper para obtener las categorías únicas
function getCategories(section) {
    const recipes = recipesData[section];
    const categories = [...new Set(recipes.map(r => r.category))];
    return categories;
}

// Helper para obtener recetas por categoría
function getRecipesByCategory(section, category) {
    return recipesData[section].filter(r => r.category === category);
}